[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "feature_extraction_pipeline"
readme = "README.md"
dynamic = [ "dependencies", "version",]

[project.scripts]
feature-extraction-pipeline = "feature_extraction_pipeline.__main__:main"

[tool.kedro]
package_name = "feature_extraction_pipeline"
project_name = "feature-extraction-pipeline"
kedro_init_version = "0.19.7"
tools = [ "Data Structure", "Kedro Viz", "Custom Logging",]
example_pipeline = "True"
source_dir = "src"

[project.entry-points."kedro.hooks"]

[tool.setuptools.dynamic.dependencies]
file = "requirements.txt"

[tool.setuptools.dynamic.version]
attr = "feature_extraction_pipeline.__version__"

[tool.setuptools.packages.find]
where = [ "src",]
namespaces = false

[tool.kedro_telemetry]
project_id = "62475f03123940ba90ba5335227ddc4e"
