minio_url: "http://localhost:9000"
minio_alias: "minio"
admin: "ufv-admin-root"
password: "admin-root"
bucket_name: "test-bucket"
save_directory: "data/malware"

# ------------------------------
# pipeline-trigger

all_mnemonic_csv_input_path: "data/malware"
all_mnemonic_csv_output_path: "results/all_mnemonic.csv"
